//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.OperazioniSoap")]
    public interface OperazioniSoap {
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento HelloWorldResult dallo spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Client.ServiceReference1.HelloWorldResponse HelloWorld(Client.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.HelloWorldResponse> HelloWorldAsync(Client.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento username dallo spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ControllaCredenziali", ReplyAction="*")]
        Client.ServiceReference1.ControllaCredenzialiResponse ControllaCredenziali(Client.ServiceReference1.ControllaCredenzialiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ControllaCredenziali", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.ControllaCredenzialiResponse> ControllaCredenzialiAsync(Client.ServiceReference1.ControllaCredenzialiRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Client.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Client.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ControllaCredenzialiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ControllaCredenziali", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.ControllaCredenzialiRequestBody Body;
        
        public ControllaCredenzialiRequest() {
        }
        
        public ControllaCredenzialiRequest(Client.ServiceReference1.ControllaCredenzialiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ControllaCredenzialiRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public ControllaCredenzialiRequestBody() {
        }
        
        public ControllaCredenzialiRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ControllaCredenzialiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ControllaCredenzialiResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.ControllaCredenzialiResponseBody Body;
        
        public ControllaCredenzialiResponse() {
        }
        
        public ControllaCredenzialiResponse(Client.ServiceReference1.ControllaCredenzialiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ControllaCredenzialiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ControllaCredenzialiResult;
        
        public ControllaCredenzialiResponseBody() {
        }
        
        public ControllaCredenzialiResponseBody(bool ControllaCredenzialiResult) {
            this.ControllaCredenzialiResult = ControllaCredenzialiResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OperazioniSoapChannel : Client.ServiceReference1.OperazioniSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperazioniSoapClient : System.ServiceModel.ClientBase<Client.ServiceReference1.OperazioniSoap>, Client.ServiceReference1.OperazioniSoap {
        
        public OperazioniSoapClient() {
        }
        
        public OperazioniSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperazioniSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperazioniSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperazioniSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.HelloWorldResponse Client.ServiceReference1.OperazioniSoap.HelloWorld(Client.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Client.ServiceReference1.HelloWorldRequest inValue = new Client.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Client.ServiceReference1.HelloWorldRequestBody();
            Client.ServiceReference1.HelloWorldResponse retVal = ((Client.ServiceReference1.OperazioniSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.HelloWorldResponse> Client.ServiceReference1.OperazioniSoap.HelloWorldAsync(Client.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            Client.ServiceReference1.HelloWorldRequest inValue = new Client.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Client.ServiceReference1.HelloWorldRequestBody();
            return ((Client.ServiceReference1.OperazioniSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.ControllaCredenzialiResponse Client.ServiceReference1.OperazioniSoap.ControllaCredenziali(Client.ServiceReference1.ControllaCredenzialiRequest request) {
            return base.Channel.ControllaCredenziali(request);
        }
        
        public bool ControllaCredenziali(string username, string password) {
            Client.ServiceReference1.ControllaCredenzialiRequest inValue = new Client.ServiceReference1.ControllaCredenzialiRequest();
            inValue.Body = new Client.ServiceReference1.ControllaCredenzialiRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Client.ServiceReference1.ControllaCredenzialiResponse retVal = ((Client.ServiceReference1.OperazioniSoap)(this)).ControllaCredenziali(inValue);
            return retVal.Body.ControllaCredenzialiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.ControllaCredenzialiResponse> Client.ServiceReference1.OperazioniSoap.ControllaCredenzialiAsync(Client.ServiceReference1.ControllaCredenzialiRequest request) {
            return base.Channel.ControllaCredenzialiAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.ControllaCredenzialiResponse> ControllaCredenzialiAsync(string username, string password) {
            Client.ServiceReference1.ControllaCredenzialiRequest inValue = new Client.ServiceReference1.ControllaCredenzialiRequest();
            inValue.Body = new Client.ServiceReference1.ControllaCredenzialiRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((Client.ServiceReference1.OperazioniSoap)(this)).ControllaCredenzialiAsync(inValue);
        }
    }
}
