//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServerLogin {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServerLogin.LoginControllerSoap")]
    public interface LoginControllerSoap {
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento username dallo spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificaCredenziali", ReplyAction="*")]
        Client.ServerLogin.VerificaCredenzialiResponse VerificaCredenziali(Client.ServerLogin.VerificaCredenzialiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificaCredenziali", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServerLogin.VerificaCredenzialiResponse> VerificaCredenzialiAsync(Client.ServerLogin.VerificaCredenzialiRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificaCredenzialiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificaCredenziali", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServerLogin.VerificaCredenzialiRequestBody Body;
        
        public VerificaCredenzialiRequest() {
        }
        
        public VerificaCredenzialiRequest(Client.ServerLogin.VerificaCredenzialiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificaCredenzialiRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public VerificaCredenzialiRequestBody() {
        }
        
        public VerificaCredenzialiRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificaCredenzialiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificaCredenzialiResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServerLogin.VerificaCredenzialiResponseBody Body;
        
        public VerificaCredenzialiResponse() {
        }
        
        public VerificaCredenzialiResponse(Client.ServerLogin.VerificaCredenzialiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificaCredenzialiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerificaCredenzialiResult;
        
        public VerificaCredenzialiResponseBody() {
        }
        
        public VerificaCredenzialiResponseBody(bool VerificaCredenzialiResult) {
            this.VerificaCredenzialiResult = VerificaCredenzialiResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginControllerSoapChannel : Client.ServerLogin.LoginControllerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginControllerSoapClient : System.ServiceModel.ClientBase<Client.ServerLogin.LoginControllerSoap>, Client.ServerLogin.LoginControllerSoap {
        
        public LoginControllerSoapClient() {
        }
        
        public LoginControllerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginControllerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginControllerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginControllerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServerLogin.VerificaCredenzialiResponse Client.ServerLogin.LoginControllerSoap.VerificaCredenziali(Client.ServerLogin.VerificaCredenzialiRequest request) {
            return base.Channel.VerificaCredenziali(request);
        }
        
        public bool VerificaCredenziali(string username, string password) {
            Client.ServerLogin.VerificaCredenzialiRequest inValue = new Client.ServerLogin.VerificaCredenzialiRequest();
            inValue.Body = new Client.ServerLogin.VerificaCredenzialiRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Client.ServerLogin.VerificaCredenzialiResponse retVal = ((Client.ServerLogin.LoginControllerSoap)(this)).VerificaCredenziali(inValue);
            return retVal.Body.VerificaCredenzialiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServerLogin.VerificaCredenzialiResponse> Client.ServerLogin.LoginControllerSoap.VerificaCredenzialiAsync(Client.ServerLogin.VerificaCredenzialiRequest request) {
            return base.Channel.VerificaCredenzialiAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServerLogin.VerificaCredenzialiResponse> VerificaCredenzialiAsync(string username, string password) {
            Client.ServerLogin.VerificaCredenzialiRequest inValue = new Client.ServerLogin.VerificaCredenzialiRequest();
            inValue.Body = new Client.ServerLogin.VerificaCredenzialiRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((Client.ServerLogin.LoginControllerSoap)(this)).VerificaCredenzialiAsync(inValue);
        }
    }
}
