//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServerLogin1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServerLogin1.RegistrazioneControllerSoap")]
    public interface RegistrazioneControllerSoap {
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento username dallo spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistraUtente", ReplyAction="*")]
        Client.ServerLogin1.RegistraUtenteResponse RegistraUtente(Client.ServerLogin1.RegistraUtenteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistraUtente", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServerLogin1.RegistraUtenteResponse> RegistraUtenteAsync(Client.ServerLogin1.RegistraUtenteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistraUtenteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistraUtente", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServerLogin1.RegistraUtenteRequestBody Body;
        
        public RegistraUtenteRequest() {
        }
        
        public RegistraUtenteRequest(Client.ServerLogin1.RegistraUtenteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistraUtenteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string domanda;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string risposta;
        
        public RegistraUtenteRequestBody() {
        }
        
        public RegistraUtenteRequestBody(string username, string password, string email, string domanda, string risposta) {
            this.username = username;
            this.password = password;
            this.email = email;
            this.domanda = domanda;
            this.risposta = risposta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistraUtenteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistraUtenteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServerLogin1.RegistraUtenteResponseBody Body;
        
        public RegistraUtenteResponse() {
        }
        
        public RegistraUtenteResponse(Client.ServerLogin1.RegistraUtenteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistraUtenteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegistraUtenteResult;
        
        public RegistraUtenteResponseBody() {
        }
        
        public RegistraUtenteResponseBody(string RegistraUtenteResult) {
            this.RegistraUtenteResult = RegistraUtenteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegistrazioneControllerSoapChannel : Client.ServerLogin1.RegistrazioneControllerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrazioneControllerSoapClient : System.ServiceModel.ClientBase<Client.ServerLogin1.RegistrazioneControllerSoap>, Client.ServerLogin1.RegistrazioneControllerSoap {
        
        public RegistrazioneControllerSoapClient() {
        }
        
        public RegistrazioneControllerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistrazioneControllerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrazioneControllerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrazioneControllerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServerLogin1.RegistraUtenteResponse Client.ServerLogin1.RegistrazioneControllerSoap.RegistraUtente(Client.ServerLogin1.RegistraUtenteRequest request) {
            return base.Channel.RegistraUtente(request);
        }
        
        public string RegistraUtente(string username, string password, string email, string domanda, string risposta) {
            Client.ServerLogin1.RegistraUtenteRequest inValue = new Client.ServerLogin1.RegistraUtenteRequest();
            inValue.Body = new Client.ServerLogin1.RegistraUtenteRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.email = email;
            inValue.Body.domanda = domanda;
            inValue.Body.risposta = risposta;
            Client.ServerLogin1.RegistraUtenteResponse retVal = ((Client.ServerLogin1.RegistrazioneControllerSoap)(this)).RegistraUtente(inValue);
            return retVal.Body.RegistraUtenteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServerLogin1.RegistraUtenteResponse> Client.ServerLogin1.RegistrazioneControllerSoap.RegistraUtenteAsync(Client.ServerLogin1.RegistraUtenteRequest request) {
            return base.Channel.RegistraUtenteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServerLogin1.RegistraUtenteResponse> RegistraUtenteAsync(string username, string password, string email, string domanda, string risposta) {
            Client.ServerLogin1.RegistraUtenteRequest inValue = new Client.ServerLogin1.RegistraUtenteRequest();
            inValue.Body = new Client.ServerLogin1.RegistraUtenteRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.email = email;
            inValue.Body.domanda = domanda;
            inValue.Body.risposta = risposta;
            return ((Client.ServerLogin1.RegistrazioneControllerSoap)(this)).RegistraUtenteAsync(inValue);
        }
    }
}
