//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServerLegaMercato {
    using System.Runtime.Serialization;
    using System;
    using Client.Dominio;
    using System.Collections.Generic;

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mercato", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Mercato : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ServerLegaMercato.Lega LegaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ServerLegaMercato.Asta[] AsteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ServerLegaMercato.Squadra[] SquadreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Client.ServerLegaMercato.Lega Lega {
            get {
                return this.LegaField;
            }
            set {
                if ((object.ReferenceEquals(this.LegaField, value) != true)) {
                    this.LegaField = value;
                    this.RaisePropertyChanged("Lega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Client.ServerLegaMercato.Asta[] Aste {
            get {
                return this.AsteField;
            }
            set {
                if ((object.ReferenceEquals(this.AsteField, value) != true)) {
                    this.AsteField = value;
                    this.RaisePropertyChanged("Aste");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Client.ServerLegaMercato.Squadra[] Squadre {
            get {
                return this.SquadreField;
            }
            set {
                if ((object.ReferenceEquals(this.SquadreField, value) != true)) {
                    this.SquadreField = value;
                    this.RaisePropertyChanged("Squadre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lega", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Lega : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeLegaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ServerLegaMercato.Squadra SquadraAdminField;
        
        private int NumeroSquadreTotaliField;
        
        private int CreditiInizialiSquadraField;
        
        private int NumeroPorField;
        
        private int NumeroDifField;
        
        private int NumeroCenField;
        
        private int NumeroAttField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ServerLegaMercato.Mercato MercatoAttivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ServerLegaMercato.ListaSvincolati ListaSvincolatiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ServerLegaMercato.Squadra[] SquadreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NomeLega {
            get {
                return this.NomeLegaField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeLegaField, value) != true)) {
                    this.NomeLegaField = value;
                    this.RaisePropertyChanged("NomeLega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Client.ServerLegaMercato.Squadra SquadraAdmin {
            get {
                return this.SquadraAdminField;
            }
            set {
                if ((object.ReferenceEquals(this.SquadraAdminField, value) != true)) {
                    this.SquadraAdminField = value;
                    this.RaisePropertyChanged("SquadraAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int NumeroSquadreTotali {
            get {
                return this.NumeroSquadreTotaliField;
            }
            set {
                if ((this.NumeroSquadreTotaliField.Equals(value) != true)) {
                    this.NumeroSquadreTotaliField = value;
                    this.RaisePropertyChanged("NumeroSquadreTotali");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CreditiInizialiSquadra {
            get {
                return this.CreditiInizialiSquadraField;
            }
            set {
                if ((this.CreditiInizialiSquadraField.Equals(value) != true)) {
                    this.CreditiInizialiSquadraField = value;
                    this.RaisePropertyChanged("CreditiInizialiSquadra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int NumeroPor {
            get {
                return this.NumeroPorField;
            }
            set {
                if ((this.NumeroPorField.Equals(value) != true)) {
                    this.NumeroPorField = value;
                    this.RaisePropertyChanged("NumeroPor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int NumeroDif {
            get {
                return this.NumeroDifField;
            }
            set {
                if ((this.NumeroDifField.Equals(value) != true)) {
                    this.NumeroDifField = value;
                    this.RaisePropertyChanged("NumeroDif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int NumeroCen {
            get {
                return this.NumeroCenField;
            }
            set {
                if ((this.NumeroCenField.Equals(value) != true)) {
                    this.NumeroCenField = value;
                    this.RaisePropertyChanged("NumeroCen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int NumeroAtt {
            get {
                return this.NumeroAttField;
            }
            set {
                if ((this.NumeroAttField.Equals(value) != true)) {
                    this.NumeroAttField = value;
                    this.RaisePropertyChanged("NumeroAtt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public Client.ServerLegaMercato.Mercato MercatoAttivo {
            get {
                return this.MercatoAttivoField;
            }
            set {
                if ((object.ReferenceEquals(this.MercatoAttivoField, value) != true)) {
                    this.MercatoAttivoField = value;
                    this.RaisePropertyChanged("MercatoAttivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public Client.ServerLegaMercato.ListaSvincolati ListaSvincolati {
            get {
                return this.ListaSvincolatiField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaSvincolatiField, value) != true)) {
                    this.ListaSvincolatiField = value;
                    this.RaisePropertyChanged("ListaSvincolati");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public Client.ServerLegaMercato.Squadra[] Squadre {
            get {
                return this.SquadreField;
            }
            set {
                if ((object.ReferenceEquals(this.SquadreField, value) != true)) {
                    this.SquadreField = value;
                    this.RaisePropertyChanged("Squadre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Asta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Asta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdAstaField;
        
        private int UltimaOffertaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ServerLegaMercato.Squadra UltimoOfferenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ServerLegaMercato.Squadra[] SquadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ServerLegaMercato.Giocatore GiocatoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdAsta {
            get {
                return this.IdAstaField;
            }
            set {
                if ((this.IdAstaField.Equals(value) != true)) {
                    this.IdAstaField = value;
                    this.RaisePropertyChanged("IdAsta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UltimaOfferta {
            get {
                return this.UltimaOffertaField;
            }
            set {
                if ((this.UltimaOffertaField.Equals(value) != true)) {
                    this.UltimaOffertaField = value;
                    this.RaisePropertyChanged("UltimaOfferta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Client.ServerLegaMercato.Squadra UltimoOfferente {
            get {
                return this.UltimoOfferenteField;
            }
            set {
                if ((object.ReferenceEquals(this.UltimoOfferenteField, value) != true)) {
                    this.UltimoOfferenteField = value;
                    this.RaisePropertyChanged("UltimoOfferente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Client.ServerLegaMercato.Squadra[] Squadre {
            get {
                return this.SquadreField;
            }
            set {
                if ((object.ReferenceEquals(this.SquadreField, value) != true)) {
                    this.SquadreField = value;
                    this.RaisePropertyChanged("Squadre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Client.ServerLegaMercato.Giocatore Giocatore {
            get {
                return this.GiocatoreField;
            }
            set {
                if ((object.ReferenceEquals(this.GiocatoreField, value) != true)) {
                    this.GiocatoreField = value;
                    this.RaisePropertyChanged("Giocatore");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        public static explicit operator Asta(List<Dominio.Asta> v)
        {
            throw new NotImplementedException();
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Squadra", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Squadra : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        private int CreditResiduiField;
        
        private int NumeroPorField;
        
        private int NumeroDifField;
        
        private int NumeroCenField;
        
        private int NumeroAttField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ServerLegaMercato.Giocatore[] GiocatoriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ServerLegaMercato.Lega LegaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ServerLegaMercato.Utente UtenteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int CreditResidui {
            get {
                return this.CreditResiduiField;
            }
            set {
                if ((this.CreditResiduiField.Equals(value) != true)) {
                    this.CreditResiduiField = value;
                    this.RaisePropertyChanged("CreditResidui");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int NumeroPor {
            get {
                return this.NumeroPorField;
            }
            set {
                if ((this.NumeroPorField.Equals(value) != true)) {
                    this.NumeroPorField = value;
                    this.RaisePropertyChanged("NumeroPor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int NumeroDif {
            get {
                return this.NumeroDifField;
            }
            set {
                if ((this.NumeroDifField.Equals(value) != true)) {
                    this.NumeroDifField = value;
                    this.RaisePropertyChanged("NumeroDif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int NumeroCen {
            get {
                return this.NumeroCenField;
            }
            set {
                if ((this.NumeroCenField.Equals(value) != true)) {
                    this.NumeroCenField = value;
                    this.RaisePropertyChanged("NumeroCen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int NumeroAtt {
            get {
                return this.NumeroAttField;
            }
            set {
                if ((this.NumeroAttField.Equals(value) != true)) {
                    this.NumeroAttField = value;
                    this.RaisePropertyChanged("NumeroAtt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public Client.ServerLegaMercato.Giocatore[] Giocatori {
            get {
                return this.GiocatoriField;
            }
            set {
                if ((object.ReferenceEquals(this.GiocatoriField, value) != true)) {
                    this.GiocatoriField = value;
                    this.RaisePropertyChanged("Giocatori");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public Client.ServerLegaMercato.Lega Lega {
            get {
                return this.LegaField;
            }
            set {
                if ((object.ReferenceEquals(this.LegaField, value) != true)) {
                    this.LegaField = value;
                    this.RaisePropertyChanged("Lega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public Client.ServerLegaMercato.Utente Utente {
            get {
                return this.UtenteField;
            }
            set {
                if ((object.ReferenceEquals(this.UtenteField, value) != true)) {
                    this.UtenteField = value;
                    this.RaisePropertyChanged("Utente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaSvincolati", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ListaSvincolati : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DataCaricamentoField;
        
        private int IdListaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ServerLegaMercato.Giocatore[] GiocatoriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime DataCaricamento {
            get {
                return this.DataCaricamentoField;
            }
            set {
                if ((this.DataCaricamentoField.Equals(value) != true)) {
                    this.DataCaricamentoField = value;
                    this.RaisePropertyChanged("DataCaricamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdLista {
            get {
                return this.IdListaField;
            }
            set {
                if ((this.IdListaField.Equals(value) != true)) {
                    this.IdListaField = value;
                    this.RaisePropertyChanged("IdLista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Client.ServerLegaMercato.Giocatore[] Giocatori {
            get {
                return this.GiocatoriField;
            }
            set {
                if ((object.ReferenceEquals(this.GiocatoriField, value) != true)) {
                    this.GiocatoriField = value;
                    this.RaisePropertyChanged("Giocatori");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Utente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Utente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        private bool IsAdminField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsAdmin {
            get {
                return this.IsAdminField;
            }
            set {
                if ((this.IsAdminField.Equals(value) != true)) {
                    this.IsAdminField = value;
                    this.RaisePropertyChanged("IsAdmin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Giocatore", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Giocatore : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeSquadraField;
        
        private int PrezzoAcquistoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NomeSquadra {
            get {
                return this.NomeSquadraField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeSquadraField, value) != true)) {
                    this.NomeSquadraField = value;
                    this.RaisePropertyChanged("NomeSquadra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PrezzoAcquisto {
            get {
                return this.PrezzoAcquistoField;
            }
            set {
                if ((this.PrezzoAcquistoField.Equals(value) != true)) {
                    this.PrezzoAcquistoField = value;
                    this.RaisePropertyChanged("PrezzoAcquisto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServerLegaMercato.GestioneMercatoControllerSoap")]
    public interface GestioneMercatoControllerSoap {
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento mercato dallo spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChiudiMercato", ReplyAction="*")]
        Client.ServerLegaMercato.ChiudiMercatoResponse ChiudiMercato(Client.ServerLegaMercato.ChiudiMercatoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChiudiMercato", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServerLegaMercato.ChiudiMercatoResponse> ChiudiMercatoAsync(Client.ServerLegaMercato.ChiudiMercatoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChiudiMercatoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChiudiMercato", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServerLegaMercato.ChiudiMercatoRequestBody Body;
        
        public ChiudiMercatoRequest() {
        }
        
        public ChiudiMercatoRequest(Client.ServerLegaMercato.ChiudiMercatoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChiudiMercatoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServerLegaMercato.Mercato mercato;
        
        public ChiudiMercatoRequestBody() {
        }
        
        public ChiudiMercatoRequestBody(Client.ServerLegaMercato.Mercato mercato) {
            this.mercato = mercato;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChiudiMercatoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChiudiMercatoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServerLegaMercato.ChiudiMercatoResponseBody Body;
        
        public ChiudiMercatoResponse() {
        }
        
        public ChiudiMercatoResponse(Client.ServerLegaMercato.ChiudiMercatoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChiudiMercatoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ChiudiMercatoResult;
        
        public ChiudiMercatoResponseBody() {
        }
        
        public ChiudiMercatoResponseBody(bool ChiudiMercatoResult) {
            this.ChiudiMercatoResult = ChiudiMercatoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GestioneMercatoControllerSoapChannel : Client.ServerLegaMercato.GestioneMercatoControllerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestioneMercatoControllerSoapClient : System.ServiceModel.ClientBase<Client.ServerLegaMercato.GestioneMercatoControllerSoap>, Client.ServerLegaMercato.GestioneMercatoControllerSoap {
        
        public GestioneMercatoControllerSoapClient() {
        }
        
        public GestioneMercatoControllerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestioneMercatoControllerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestioneMercatoControllerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestioneMercatoControllerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServerLegaMercato.ChiudiMercatoResponse Client.ServerLegaMercato.GestioneMercatoControllerSoap.ChiudiMercato(Client.ServerLegaMercato.ChiudiMercatoRequest request) {
            return base.Channel.ChiudiMercato(request);
        }
        
        public bool ChiudiMercato(Client.ServerLegaMercato.Mercato mercato) {
            Client.ServerLegaMercato.ChiudiMercatoRequest inValue = new Client.ServerLegaMercato.ChiudiMercatoRequest();
            inValue.Body = new Client.ServerLegaMercato.ChiudiMercatoRequestBody();
            inValue.Body.mercato = mercato;
            Client.ServerLegaMercato.ChiudiMercatoResponse retVal = ((Client.ServerLegaMercato.GestioneMercatoControllerSoap)(this)).ChiudiMercato(inValue);
            return retVal.Body.ChiudiMercatoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServerLegaMercato.ChiudiMercatoResponse> Client.ServerLegaMercato.GestioneMercatoControllerSoap.ChiudiMercatoAsync(Client.ServerLegaMercato.ChiudiMercatoRequest request) {
            return base.Channel.ChiudiMercatoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServerLegaMercato.ChiudiMercatoResponse> ChiudiMercatoAsync(Client.ServerLegaMercato.Mercato mercato) {
            Client.ServerLegaMercato.ChiudiMercatoRequest inValue = new Client.ServerLegaMercato.ChiudiMercatoRequest();
            inValue.Body = new Client.ServerLegaMercato.ChiudiMercatoRequestBody();
            inValue.Body.mercato = mercato;
            return ((Client.ServerLegaMercato.GestioneMercatoControllerSoap)(this)).ChiudiMercatoAsync(inValue);
        }
    }
}
